//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.MvcUI.KullaniciSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KullaniciDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        private System.Nullable<int> YasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.Nullable<System.DateTime> EhliyetAlimTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Yas {
            get {
                return this.YasField;
            }
            set {
                if ((this.YasField.Equals(value) != true)) {
                    this.YasField = value;
                    this.RaisePropertyChanged("Yas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> EhliyetAlimTarihi {
            get {
                return this.EhliyetAlimTarihiField;
            }
            set {
                if ((this.EhliyetAlimTarihiField.Equals(value) != true)) {
                    this.EhliyetAlimTarihiField = value;
                    this.RaisePropertyChanged("EhliyetAlimTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KullaniciSoapService.KullaniciSoapServiceSoap")]
    public interface KullaniciSoapServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse HelloWorld(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse> HelloWorldAsync(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name KullaniciListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciListele", ReplyAction="*")]
        AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse KullaniciListele(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciListele", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse> KullaniciListeleAsync(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciListele", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequestBody Body;
        
        public KullaniciListeleRequest() {
        }
        
        public KullaniciListeleRequest(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class KullaniciListeleRequestBody {
        
        public KullaniciListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponseBody Body;
        
        public KullaniciListeleResponse() {
        }
        
        public KullaniciListeleResponse(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.MvcUI.KullaniciSoapService.KullaniciDTO[] KullaniciListeleResult;
        
        public KullaniciListeleResponseBody() {
        }
        
        public KullaniciListeleResponseBody(AracKiralama.MvcUI.KullaniciSoapService.KullaniciDTO[] KullaniciListeleResult) {
            this.KullaniciListeleResult = KullaniciListeleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KullaniciSoapServiceSoapChannel : AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciSoapServiceSoapClient : System.ServiceModel.ClientBase<AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap>, AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap {
        
        public KullaniciSoapServiceSoapClient() {
        }
        
        public KullaniciSoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciSoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciSoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciSoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap.HelloWorld(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest inValue = new AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest();
            inValue.Body = new AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequestBody();
            AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse retVal = ((AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse> AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap.HelloWorldAsync(AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.HelloWorldResponse> HelloWorldAsync() {
            AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest inValue = new AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequest();
            inValue.Body = new AracKiralama.MvcUI.KullaniciSoapService.HelloWorldRequestBody();
            return ((AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap.KullaniciListele(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest request) {
            return base.Channel.KullaniciListele(request);
        }
        
        public AracKiralama.MvcUI.KullaniciSoapService.KullaniciDTO[] KullaniciListele() {
            AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest inValue = new AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest();
            inValue.Body = new AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequestBody();
            AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse retVal = ((AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap)(this)).KullaniciListele(inValue);
            return retVal.Body.KullaniciListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse> AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap.KullaniciListeleAsync(AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest request) {
            return base.Channel.KullaniciListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleResponse> KullaniciListeleAsync() {
            AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest inValue = new AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequest();
            inValue.Body = new AracKiralama.MvcUI.KullaniciSoapService.KullaniciListeleRequestBody();
            return ((AracKiralama.MvcUI.KullaniciSoapService.KullaniciSoapServiceSoap)(this)).KullaniciListeleAsync(inValue);
        }
    }
}
