//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Web.UI.KullaniciServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KullaniciDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.Nullable<System.DateTime> EhliyetAlimTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        private System.Nullable<System.DateTime> DogumTarihiField;
        
        private System.Nullable<int> RoleIdField;
        
        private System.Nullable<int> SirketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KullaniciId {
            get {
                return this.KullaniciIdField;
            }
            set {
                if ((this.KullaniciIdField.Equals(value) != true)) {
                    this.KullaniciIdField = value;
                    this.RaisePropertyChanged("KullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> EhliyetAlimTarihi {
            get {
                return this.EhliyetAlimTarihiField;
            }
            set {
                if ((this.EhliyetAlimTarihiField.Equals(value) != true)) {
                    this.EhliyetAlimTarihiField = value;
                    this.RaisePropertyChanged("EhliyetAlimTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KullaniciServis.KullaniciServisSoap")]
    public interface KullaniciServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        AracKiralama.Web.UI.KullaniciServis.AddResponse Add(AracKiralama.Web.UI.KullaniciServis.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.AddResponse> AddAsync(AracKiralama.Web.UI.KullaniciServis.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        AracKiralama.Web.UI.KullaniciServis.GetResponse Get(AracKiralama.Web.UI.KullaniciServis.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetResponse> GetAsync(AracKiralama.Web.UI.KullaniciServis.GetRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        AracKiralama.Web.UI.KullaniciServis.GetAllResponse GetAll(AracKiralama.Web.UI.KullaniciServis.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetAllResponse> GetAllAsync(AracKiralama.Web.UI.KullaniciServis.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name eposta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciGiris", ReplyAction="*")]
        AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse KullaniciGiris(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciGiris", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse> KullaniciGirisAsync(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AracKiralama.Web.UI.KullaniciServis.UpdateResponse Update(AracKiralama.Web.UI.KullaniciServis.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.UpdateResponse> UpdateAsync(AracKiralama.Web.UI.KullaniciServis.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(AracKiralama.Web.UI.KullaniciServis.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(AracKiralama.Web.UI.KullaniciServis.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(AracKiralama.Web.UI.KullaniciServis.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(AracKiralama.Web.UI.KullaniciServis.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(AracKiralama.Web.UI.KullaniciServis.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(AracKiralama.Web.UI.KullaniciServis.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciGirisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciGiris", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequestBody Body;
        
        public KullaniciGirisRequest() {
        }
        
        public KullaniciGirisRequest(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciGirisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eposta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sifre;
        
        public KullaniciGirisRequestBody() {
        }
        
        public KullaniciGirisRequestBody(string eposta, string sifre) {
            this.eposta = eposta;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciGirisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciGirisResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponseBody Body;
        
        public KullaniciGirisResponse() {
        }
        
        public KullaniciGirisResponse(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciGirisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO KullaniciGirisResult;
        
        public KullaniciGirisResponseBody() {
        }
        
        public KullaniciGirisResponseBody(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO KullaniciGirisResult) {
            this.KullaniciGirisResult = KullaniciGirisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AracKiralama.Web.UI.KullaniciServis.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.Web.UI.KullaniciServis.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AracKiralama.Web.UI.KullaniciServis.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KullaniciServisSoapChannel : AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciServisSoapClient : System.ServiceModel.ClientBase<AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap>, AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap {
        
        public KullaniciServisSoapClient() {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.Web.UI.KullaniciServis.AddResponse AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.Add(AracKiralama.Web.UI.KullaniciServis.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            AracKiralama.Web.UI.KullaniciServis.AddRequest inValue = new AracKiralama.Web.UI.KullaniciServis.AddRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.AddRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.Web.UI.KullaniciServis.AddResponse retVal = ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.AddResponse> AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.AddAsync(AracKiralama.Web.UI.KullaniciServis.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.AddResponse> AddAsync(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            AracKiralama.Web.UI.KullaniciServis.AddRequest inValue = new AracKiralama.Web.UI.KullaniciServis.AddRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.AddRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).AddAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.Web.UI.KullaniciServis.GetResponse AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.Get(AracKiralama.Web.UI.KullaniciServis.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO Get(int id) {
            AracKiralama.Web.UI.KullaniciServis.GetRequest inValue = new AracKiralama.Web.UI.KullaniciServis.GetRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.GetRequestBody();
            inValue.Body.id = id;
            AracKiralama.Web.UI.KullaniciServis.GetResponse retVal = ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetResponse> AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.GetAsync(AracKiralama.Web.UI.KullaniciServis.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetResponse> GetAsync(int id) {
            AracKiralama.Web.UI.KullaniciServis.GetRequest inValue = new AracKiralama.Web.UI.KullaniciServis.GetRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.GetRequestBody();
            inValue.Body.id = id;
            return ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.Web.UI.KullaniciServis.GetAllResponse AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.GetAll(AracKiralama.Web.UI.KullaniciServis.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO[] GetAll() {
            AracKiralama.Web.UI.KullaniciServis.GetAllRequest inValue = new AracKiralama.Web.UI.KullaniciServis.GetAllRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.GetAllRequestBody();
            AracKiralama.Web.UI.KullaniciServis.GetAllResponse retVal = ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetAllResponse> AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.GetAllAsync(AracKiralama.Web.UI.KullaniciServis.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.GetAllResponse> GetAllAsync() {
            AracKiralama.Web.UI.KullaniciServis.GetAllRequest inValue = new AracKiralama.Web.UI.KullaniciServis.GetAllRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.GetAllRequestBody();
            return ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.KullaniciGiris(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest request) {
            return base.Channel.KullaniciGiris(request);
        }
        
        public AracKiralama.Web.UI.KullaniciServis.KullaniciDTO KullaniciGiris(string eposta, string sifre) {
            AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest inValue = new AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequestBody();
            inValue.Body.eposta = eposta;
            inValue.Body.sifre = sifre;
            AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse retVal = ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).KullaniciGiris(inValue);
            return retVal.Body.KullaniciGirisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse> AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.KullaniciGirisAsync(AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest request) {
            return base.Channel.KullaniciGirisAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.KullaniciGirisResponse> KullaniciGirisAsync(string eposta, string sifre) {
            AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest inValue = new AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.KullaniciGirisRequestBody();
            inValue.Body.eposta = eposta;
            inValue.Body.sifre = sifre;
            return ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).KullaniciGirisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.Web.UI.KullaniciServis.UpdateResponse AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.Update(AracKiralama.Web.UI.KullaniciServis.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            AracKiralama.Web.UI.KullaniciServis.UpdateRequest inValue = new AracKiralama.Web.UI.KullaniciServis.UpdateRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.UpdateRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.Web.UI.KullaniciServis.UpdateResponse retVal = ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.UpdateResponse> AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap.UpdateAsync(AracKiralama.Web.UI.KullaniciServis.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.Web.UI.KullaniciServis.UpdateResponse> UpdateAsync(AracKiralama.Web.UI.KullaniciServis.KullaniciDTO entity) {
            AracKiralama.Web.UI.KullaniciServis.UpdateRequest inValue = new AracKiralama.Web.UI.KullaniciServis.UpdateRequest();
            inValue.Body = new AracKiralama.Web.UI.KullaniciServis.UpdateRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.Web.UI.KullaniciServis.KullaniciServisSoap)(this)).UpdateAsync(inValue);
        }
    }
}
