//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.WebUI.AracServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AracDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AracDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private System.Nullable<int> EhliyetYasiField;
        
        private System.Nullable<int> MinYasSiniriField;
        
        private System.Nullable<int> GunlukSinirKMField;
        
        private System.Nullable<long> KendiAnlikKMField;
        
        private System.Nullable<bool> AirBagField;
        
        private System.Nullable<int> BagajHacmiField;
        
        private System.Nullable<int> KoltukSayisiField;
        
        private System.Nullable<decimal> GunlukKiralikFiyatField;
        
        private System.Nullable<int> SirketIDField;
        
        private System.Nullable<bool> RezerveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> MinYasSiniri {
            get {
                return this.MinYasSiniriField;
            }
            set {
                if ((this.MinYasSiniriField.Equals(value) != true)) {
                    this.MinYasSiniriField = value;
                    this.RaisePropertyChanged("MinYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> GunlukSinirKM {
            get {
                return this.GunlukSinirKMField;
            }
            set {
                if ((this.GunlukSinirKMField.Equals(value) != true)) {
                    this.GunlukSinirKMField = value;
                    this.RaisePropertyChanged("GunlukSinirKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<long> KendiAnlikKM {
            get {
                return this.KendiAnlikKMField;
            }
            set {
                if ((this.KendiAnlikKMField.Equals(value) != true)) {
                    this.KendiAnlikKMField = value;
                    this.RaisePropertyChanged("KendiAnlikKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> AirBag {
            get {
                return this.AirBagField;
            }
            set {
                if ((this.AirBagField.Equals(value) != true)) {
                    this.AirBagField = value;
                    this.RaisePropertyChanged("AirBag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> GunlukKiralikFiyat {
            get {
                return this.GunlukKiralikFiyatField;
            }
            set {
                if ((this.GunlukKiralikFiyatField.Equals(value) != true)) {
                    this.GunlukKiralikFiyatField = value;
                    this.RaisePropertyChanged("GunlukKiralikFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((this.SirketIDField.Equals(value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<bool> Rezerve {
            get {
                return this.RezerveField;
            }
            set {
                if ((this.RezerveField.Equals(value) != true)) {
                    this.RezerveField = value;
                    this.RaisePropertyChanged("Rezerve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Resim {
            get {
                return this.ResimField;
            }
            set {
                if ((object.ReferenceEquals(this.ResimField, value) != true)) {
                    this.ResimField = value;
                    this.RaisePropertyChanged("Resim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracServis.AracServisSoap")]
    public interface AracServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        AracKiralama.WebUI.AracServis.AddResponse Add(AracKiralama.WebUI.AracServis.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.AddResponse> AddAsync(AracKiralama.WebUI.AracServis.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        AracKiralama.WebUI.AracServis.GetResponse Get(AracKiralama.WebUI.AracServis.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetResponse> GetAsync(AracKiralama.WebUI.AracServis.GetRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        AracKiralama.WebUI.AracServis.GetAllResponse GetAll(AracKiralama.WebUI.AracServis.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetAllResponse> GetAllAsync(AracKiralama.WebUI.AracServis.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AracKiralama.WebUI.AracServis.UpdateResponse Update(AracKiralama.WebUI.AracServis.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.UpdateResponse> UpdateAsync(AracKiralama.WebUI.AracServis.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(AracKiralama.WebUI.AracServis.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.AracServis.AracDTO entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(AracKiralama.WebUI.AracServis.AracDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(AracKiralama.WebUI.AracServis.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(bool AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(AracKiralama.WebUI.AracServis.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(AracKiralama.WebUI.AracServis.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.AracServis.AracDTO GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(AracKiralama.WebUI.AracServis.AracDTO GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(AracKiralama.WebUI.AracServis.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(AracKiralama.WebUI.AracServis.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<AracKiralama.WebUI.AracServis.AracDTO> GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(System.Collections.Generic.List<AracKiralama.WebUI.AracServis.AracDTO> GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AracKiralama.WebUI.AracServis.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.AracServis.AracDTO entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AracKiralama.WebUI.AracServis.AracDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.AracServis.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AracKiralama.WebUI.AracServis.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracServisSoapChannel : AracKiralama.WebUI.AracServis.AracServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracServisSoapClient : System.ServiceModel.ClientBase<AracKiralama.WebUI.AracServis.AracServisSoap>, AracKiralama.WebUI.AracServis.AracServisSoap {
        
        public AracServisSoapClient() {
        }
        
        public AracServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.AracServis.AddResponse AracKiralama.WebUI.AracServis.AracServisSoap.Add(AracKiralama.WebUI.AracServis.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public bool Add(AracKiralama.WebUI.AracServis.AracDTO entity) {
            AracKiralama.WebUI.AracServis.AddRequest inValue = new AracKiralama.WebUI.AracServis.AddRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.AddRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.WebUI.AracServis.AddResponse retVal = ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.AddResponse> AracKiralama.WebUI.AracServis.AracServisSoap.AddAsync(AracKiralama.WebUI.AracServis.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.AddResponse> AddAsync(AracKiralama.WebUI.AracServis.AracDTO entity) {
            AracKiralama.WebUI.AracServis.AddRequest inValue = new AracKiralama.WebUI.AracServis.AddRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.AddRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).AddAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.AracServis.GetResponse AracKiralama.WebUI.AracServis.AracServisSoap.Get(AracKiralama.WebUI.AracServis.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public AracKiralama.WebUI.AracServis.AracDTO Get(int id) {
            AracKiralama.WebUI.AracServis.GetRequest inValue = new AracKiralama.WebUI.AracServis.GetRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.GetRequestBody();
            inValue.Body.id = id;
            AracKiralama.WebUI.AracServis.GetResponse retVal = ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetResponse> AracKiralama.WebUI.AracServis.AracServisSoap.GetAsync(AracKiralama.WebUI.AracServis.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetResponse> GetAsync(int id) {
            AracKiralama.WebUI.AracServis.GetRequest inValue = new AracKiralama.WebUI.AracServis.GetRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.GetRequestBody();
            inValue.Body.id = id;
            return ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.AracServis.GetAllResponse AracKiralama.WebUI.AracServis.AracServisSoap.GetAll(AracKiralama.WebUI.AracServis.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public System.Collections.Generic.List<AracKiralama.WebUI.AracServis.AracDTO> GetAll() {
            AracKiralama.WebUI.AracServis.GetAllRequest inValue = new AracKiralama.WebUI.AracServis.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.GetAllRequestBody();
            AracKiralama.WebUI.AracServis.GetAllResponse retVal = ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetAllResponse> AracKiralama.WebUI.AracServis.AracServisSoap.GetAllAsync(AracKiralama.WebUI.AracServis.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.GetAllResponse> GetAllAsync() {
            AracKiralama.WebUI.AracServis.GetAllRequest inValue = new AracKiralama.WebUI.AracServis.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.GetAllRequestBody();
            return ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.AracServis.UpdateResponse AracKiralama.WebUI.AracServis.AracServisSoap.Update(AracKiralama.WebUI.AracServis.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(AracKiralama.WebUI.AracServis.AracDTO entity) {
            AracKiralama.WebUI.AracServis.UpdateRequest inValue = new AracKiralama.WebUI.AracServis.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.UpdateRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.WebUI.AracServis.UpdateResponse retVal = ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.UpdateResponse> AracKiralama.WebUI.AracServis.AracServisSoap.UpdateAsync(AracKiralama.WebUI.AracServis.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.AracServis.UpdateResponse> UpdateAsync(AracKiralama.WebUI.AracServis.AracDTO entity) {
            AracKiralama.WebUI.AracServis.UpdateRequest inValue = new AracKiralama.WebUI.AracServis.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.AracServis.UpdateRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.WebUI.AracServis.AracServisSoap)(this)).UpdateAsync(inValue);
        }
    }
}
