//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.WinFormUI.AracSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AracDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AracDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private System.Nullable<int> BagajHacmiField;
        
        private System.Nullable<byte> KoltukSayisiField;
        
        private System.Nullable<decimal> GunlukKiralikFiyatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<byte> KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> GunlukKiralikFiyat {
            get {
                return this.GunlukKiralikFiyatField;
            }
            set {
                if ((this.GunlukKiralikFiyatField.Equals(value) != true)) {
                    this.GunlukKiralikFiyatField = value;
                    this.RaisePropertyChanged("GunlukKiralikFiyat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracSoapService.AracSOAPServiceSoap")]
    public interface AracSOAPServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse HelloWorld(AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse> HelloWorldAsync(AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AracListeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracListe", ReplyAction="*")]
        AracKiralama.WinFormUI.AracSoapService.AracListeResponse AracListe(AracKiralama.WinFormUI.AracSoapService.AracListeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracListe", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.AracListeResponse> AracListeAsync(AracKiralama.WinFormUI.AracSoapService.AracListeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        bool AracEkle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AracEkleAsync();
        
        // CODEGEN: Generating message contract since element name DenemeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deneme", ReplyAction="*")]
        AracKiralama.WinFormUI.AracSoapService.DenemeResponse Deneme(AracKiralama.WinFormUI.AracSoapService.DenemeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deneme", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.DenemeResponse> DenemeAsync(AracKiralama.WinFormUI.AracSoapService.DenemeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AracKiralama.WinFormUI.AracSoapService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AracKiralama.WinFormUI.AracSoapService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracListeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracListe", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.AracListeRequestBody Body;
        
        public AracListeRequest() {
        }
        
        public AracListeRequest(AracKiralama.WinFormUI.AracSoapService.AracListeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AracListeRequestBody {
        
        public AracListeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracListeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracListeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.AracListeResponseBody Body;
        
        public AracListeResponse() {
        }
        
        public AracListeResponse(AracKiralama.WinFormUI.AracSoapService.AracListeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracListeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<AracKiralama.WinFormUI.AracSoapService.AracDTO> AracListeResult;
        
        public AracListeResponseBody() {
        }
        
        public AracListeResponseBody(System.Collections.Generic.List<AracKiralama.WinFormUI.AracSoapService.AracDTO> AracListeResult) {
            this.AracListeResult = AracListeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DenemeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deneme", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.DenemeRequestBody Body;
        
        public DenemeRequest() {
        }
        
        public DenemeRequest(AracKiralama.WinFormUI.AracSoapService.DenemeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DenemeRequestBody {
        
        public DenemeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DenemeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DenemeResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.DenemeResponseBody Body;
        
        public DenemeResponse() {
        }
        
        public DenemeResponse(AracKiralama.WinFormUI.AracSoapService.DenemeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DenemeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WinFormUI.AracSoapService.AracDTO DenemeResult;
        
        public DenemeResponseBody() {
        }
        
        public DenemeResponseBody(AracKiralama.WinFormUI.AracSoapService.AracDTO DenemeResult) {
            this.DenemeResult = DenemeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracSOAPServiceSoapChannel : AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracSOAPServiceSoapClient : System.ServiceModel.ClientBase<AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap>, AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap {
        
        public AracSOAPServiceSoapClient() {
        }
        
        public AracSOAPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracSOAPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracSOAPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracSOAPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.HelloWorld(AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest inValue = new AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.HelloWorldRequestBody();
            AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse retVal = ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse> AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.HelloWorldAsync(AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.HelloWorldResponse> HelloWorldAsync() {
            AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest inValue = new AracKiralama.WinFormUI.AracSoapService.HelloWorldRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.HelloWorldRequestBody();
            return ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WinFormUI.AracSoapService.AracListeResponse AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.AracListe(AracKiralama.WinFormUI.AracSoapService.AracListeRequest request) {
            return base.Channel.AracListe(request);
        }
        
        public System.Collections.Generic.List<AracKiralama.WinFormUI.AracSoapService.AracDTO> AracListe() {
            AracKiralama.WinFormUI.AracSoapService.AracListeRequest inValue = new AracKiralama.WinFormUI.AracSoapService.AracListeRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.AracListeRequestBody();
            AracKiralama.WinFormUI.AracSoapService.AracListeResponse retVal = ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).AracListe(inValue);
            return retVal.Body.AracListeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.AracListeResponse> AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.AracListeAsync(AracKiralama.WinFormUI.AracSoapService.AracListeRequest request) {
            return base.Channel.AracListeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.AracListeResponse> AracListeAsync() {
            AracKiralama.WinFormUI.AracSoapService.AracListeRequest inValue = new AracKiralama.WinFormUI.AracSoapService.AracListeRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.AracListeRequestBody();
            return ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).AracListeAsync(inValue);
        }
        
        public bool AracEkle() {
            return base.Channel.AracEkle();
        }
        
        public System.Threading.Tasks.Task<bool> AracEkleAsync() {
            return base.Channel.AracEkleAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WinFormUI.AracSoapService.DenemeResponse AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.Deneme(AracKiralama.WinFormUI.AracSoapService.DenemeRequest request) {
            return base.Channel.Deneme(request);
        }
        
        public AracKiralama.WinFormUI.AracSoapService.AracDTO Deneme() {
            AracKiralama.WinFormUI.AracSoapService.DenemeRequest inValue = new AracKiralama.WinFormUI.AracSoapService.DenemeRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.DenemeRequestBody();
            AracKiralama.WinFormUI.AracSoapService.DenemeResponse retVal = ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).Deneme(inValue);
            return retVal.Body.DenemeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.DenemeResponse> AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap.DenemeAsync(AracKiralama.WinFormUI.AracSoapService.DenemeRequest request) {
            return base.Channel.DenemeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WinFormUI.AracSoapService.DenemeResponse> DenemeAsync() {
            AracKiralama.WinFormUI.AracSoapService.DenemeRequest inValue = new AracKiralama.WinFormUI.AracSoapService.DenemeRequest();
            inValue.Body = new AracKiralama.WinFormUI.AracSoapService.DenemeRequestBody();
            return ((AracKiralama.WinFormUI.AracSoapService.AracSOAPServiceSoap)(this)).DenemeAsync(inValue);
        }
    }
}
