//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.MvcUI.KiralikServiceSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KiralikDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KiralikDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KiralikIdField;
        
        private System.Nullable<int> AracIDField;
        
        private System.Nullable<int> KullaniciIDField;
        
        private System.Nullable<System.DateTime> Alis_TarihiField;
        
        private System.Nullable<System.DateTime> Veris_TarihiField;
        
        private System.Nullable<long> VerilisKmField;
        
        private System.Nullable<decimal> AlinanUcretField;
        
        private System.Nullable<bool> IadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KiralikId {
            get {
                return this.KiralikIdField;
            }
            set {
                if ((this.KiralikIdField.Equals(value) != true)) {
                    this.KiralikIdField = value;
                    this.RaisePropertyChanged("KiralikId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> AracID {
            get {
                return this.AracIDField;
            }
            set {
                if ((this.AracIDField.Equals(value) != true)) {
                    this.AracIDField = value;
                    this.RaisePropertyChanged("AracID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Alis_Tarihi {
            get {
                return this.Alis_TarihiField;
            }
            set {
                if ((this.Alis_TarihiField.Equals(value) != true)) {
                    this.Alis_TarihiField = value;
                    this.RaisePropertyChanged("Alis_Tarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Veris_Tarihi {
            get {
                return this.Veris_TarihiField;
            }
            set {
                if ((this.Veris_TarihiField.Equals(value) != true)) {
                    this.Veris_TarihiField = value;
                    this.RaisePropertyChanged("Veris_Tarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<long> VerilisKm {
            get {
                return this.VerilisKmField;
            }
            set {
                if ((this.VerilisKmField.Equals(value) != true)) {
                    this.VerilisKmField = value;
                    this.RaisePropertyChanged("VerilisKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> AlinanUcret {
            get {
                return this.AlinanUcretField;
            }
            set {
                if ((this.AlinanUcretField.Equals(value) != true)) {
                    this.AlinanUcretField = value;
                    this.RaisePropertyChanged("AlinanUcret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> Iade {
            get {
                return this.IadeField;
            }
            set {
                if ((this.IadeField.Equals(value) != true)) {
                    this.IadeField = value;
                    this.RaisePropertyChanged("Iade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KiralikServiceSoap.KiralikServiceSoap")]
    public interface KiralikServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        AracKiralama.MvcUI.KiralikServiceSoap.AddResponse Add(AracKiralama.MvcUI.KiralikServiceSoap.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.AddResponse> AddAsync(AracKiralama.MvcUI.KiralikServiceSoap.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        AracKiralama.MvcUI.KiralikServiceSoap.GetResponse Get(AracKiralama.MvcUI.KiralikServiceSoap.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetResponse> GetAsync(AracKiralama.MvcUI.KiralikServiceSoap.GetRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse GetAll(AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse> GetAllAsync(AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse Update(AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse> UpdateAsync(AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(AracKiralama.MvcUI.KiralikServiceSoap.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(AracKiralama.MvcUI.KiralikServiceSoap.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(AracKiralama.MvcUI.KiralikServiceSoap.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(AracKiralama.MvcUI.KiralikServiceSoap.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KiralikServiceSoapChannel : AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KiralikServiceSoapClient : System.ServiceModel.ClientBase<AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap>, AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap {
        
        public KiralikServiceSoapClient() {
        }
        
        public KiralikServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KiralikServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KiralikServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KiralikServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KiralikServiceSoap.AddResponse AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.Add(AracKiralama.MvcUI.KiralikServiceSoap.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            AracKiralama.MvcUI.KiralikServiceSoap.AddRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.AddRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.AddRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.MvcUI.KiralikServiceSoap.AddResponse retVal = ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.AddResponse> AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.AddAsync(AracKiralama.MvcUI.KiralikServiceSoap.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.AddResponse> AddAsync(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            AracKiralama.MvcUI.KiralikServiceSoap.AddRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.AddRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.AddRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).AddAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KiralikServiceSoap.GetResponse AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.Get(AracKiralama.MvcUI.KiralikServiceSoap.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO Get(int id) {
            AracKiralama.MvcUI.KiralikServiceSoap.GetRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.GetRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.GetRequestBody();
            inValue.Body.id = id;
            AracKiralama.MvcUI.KiralikServiceSoap.GetResponse retVal = ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetResponse> AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.GetAsync(AracKiralama.MvcUI.KiralikServiceSoap.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetResponse> GetAsync(int id) {
            AracKiralama.MvcUI.KiralikServiceSoap.GetRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.GetRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.GetRequestBody();
            inValue.Body.id = id;
            return ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.GetAll(AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO[] GetAll() {
            AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequestBody();
            AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse retVal = ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse> AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.GetAllAsync(AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.GetAllResponse> GetAllAsync() {
            AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.GetAllRequestBody();
            return ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.Update(AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequestBody();
            inValue.Body.entity = entity;
            AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse retVal = ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse> AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap.UpdateAsync(AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.MvcUI.KiralikServiceSoap.UpdateResponse> UpdateAsync(AracKiralama.MvcUI.KiralikServiceSoap.KiralikDTO entity) {
            AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest inValue = new AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequest();
            inValue.Body = new AracKiralama.MvcUI.KiralikServiceSoap.UpdateRequestBody();
            inValue.Body.entity = entity;
            return ((AracKiralama.MvcUI.KiralikServiceSoap.KiralikServiceSoap)(this)).UpdateAsync(inValue);
        }
    }
}
